spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: "file:/home/uncyzer/IdeaProjects/mbds-tp-note/config-repo"
  profiles:
    active: native
server:
  port: 9999