spring:
  application:
    name: customer
  datasource:
    url: jdbc:h2:mem:customer
  h2:
    console:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

a: 10
b: 20
c: 40