spring:
  application:
    name: customer
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9999}
eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}