spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8888
management:
  endpoints:
    jmx:
      exposure:
        include: "*"